from enum import StrEnum


class StorageLocation(StrEnum):
    # Logical user-owned media storage shared by current persisted resource models.
    USER_MEDIA = "USER_MEDIA"
    # Private operational artifacts generated by application maintenance.
    SYSTEM_ARTIFACTS = "SYSTEM_ARTIFACTS"


class StorageUserPurpose(StrEnum):
    # Original files supplied directly by an import request.
    IMPORT_SOURCE = "IMPORT_SOURCE"
    # Files downloaded or generated while processing an import.
    IMPORT_DERIVED = "IMPORT_DERIVED"
    # Media owned by a persisted recipe, including generated covers.
    RECIPE_MEDIA = "RECIPE_MEDIA"


class StorageSystemPurpose(StrEnum):
    # Private structured diagnostics generated by maintenance operations.
    MAINTENANCE_REPORT = "MAINTENANCE_REPORT"
