IMPORT_LOG_COMPONENT = "recipes.import"
IMPORT_LOG_PREFIX = f"[{IMPORT_LOG_COMPONENT}]"

IMPORT_VIDEO_LOG_COMPONENT = f"{IMPORT_LOG_COMPONENT}.video"
IMPORT_VIDEO_LOG_PREFIX = f"[{IMPORT_VIDEO_LOG_COMPONENT}]"
